modLoader = "javafml"
loaderVersion = "[4,)"
issueTrackerURL = "https://github.com/Aruloci/CobEffectiveness/issues"
license = "GPL-3.0"

[[mods]]
modId = "cobblemon_effectiveness"
version = "${version}"
displayName = "Cobblemon Effectiveness"
authors = "Aruloci"
description = '''
Display type effectiveness in Pokemon battles
'''
logoFile = "src/main/resources/assets/cobeffectiveness/icon.png"

[[dependencies.cobblemon_effectiveness]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_effectiveness]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobblemon_effectiveness]]
modId="cobblemon"
type="required"
versionRange="[1.6.1,)"
ordering="NONE"
side="BOTH"

[[mixins]]
config = "cobeffectiveness.mixins.json"
