modLoader = "javafml"
loaderVersion = "[4,)"
#issueTrackerURL = ""
license = "GPL-3.0"

[[mods]]
modId = "cobeffectiveness"
version = "${version}"
displayName = "CobEffectiveness"
authors = "Aruloci"
description = '''
A Minecraft mod for Cobblemon to display type effectiveness in Pokemon battles
'''
#logoFile = ""

[[dependencies.cobeffectiveness]]
modId = "neoforge"
type = "required"
versionRange = "[21.1,)"
ordering = "NONE"
side = "BOTH"

[[dependencies.cobeffectiveness]]
modId = "minecraft"
type = "required"
versionRange = "[1.21.1,)"
ordering = "NONE"
side = "BOTH"

[[mixins]]
config = "cobeffectiveness.mixins.json"
